config/routes.rb
Rails.application.routes.draw do

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  resources :problems, controller: :ideas, type: 'Problem', :concerns => :paginatable
  resources :ideas do
    put :sort
    delete :unlike
  end

  resources :users, only: :show

  resources :tags, only: :index

  root to: 'home#index'
  get '/about' => 'home#about'

  get '/auth/:provvider/callback' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout

  mount Markdown::API => '/'

end

app/models/idea.rb
class Idea < ActiveRecord::Base

  has_many :relationships, foreign_key: "relating_id"
  has_many :related_ideas, through: :relationships, source: :related

  has_many :reverse_relationships, foreign_key: "related_id", class_name: "Relationship"
  has_many :relating_ideas, through: :reverse_relationships, source: :relating

  belongs_to :owner, class_name: 'User'
  delegate :name, :image_url, to: :owner, prefix: true

  has_many :like_ideas
  has_many :liked_users, through: :like_ideas, source: :user

  has_many :rating_ideas
  has_many :rated_users, through: :rating_ideas, source: :user

  has_many :tags
  has_many :attached_tags, through: :tags

  mount_uploader :file, FileUploader

  include RankedModel
  ranks :row_order

  validates :title, presence: true
  validates :owner_id, presence: true

  def self.types
    %w(Problem)
  end

  def to_partial_path
    'ideas/idea'
  end

  def submitted_by?(user)
    return false unless user
    owner_id == user.id
  end

  def relating?(another_idea)
    relationships.find_by(related_id: another_idea.id)
  end

  def relate!(another_idea)
    relationships.create!(related_id: another_idea.id)
  end

  def unrelate!(another_idea)
    relationships.find_by(related_id: another_idea.id).destroy
  end

  def rating?(user)
    rating = rating_ideas.find_by(user_id: user.id)
  end

  def rate!(user, key, value)
    rating = rating_ideas.find_or_create_by!(user_id: user.id)

    case key
    when :impact
      rating.impact = value
    when :frequency
      rating.frequency = value
    end

    rating.save!
  end

end

app/models/like_idea.rb
class LikeIdea < ActiveRecord::Base
  belongs_to :user
  belongs_to :idea
end

app/models/problem.rb
class Problem < Idea
end

app/models/rating_idea.rb
class RatingIdea < ActiveRecord::Base
  belongs_to :user
  belongs_to :idea
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base

  belongs_to :relating, class_name: "Idea"
  belongs_to :related, class_name: "Idea"

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :user
  belongs_to :idea
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :submitted_ideas, class_name: 'Idea', foreign_key: :owner_id

  has_many :like_ideas
  has_many :ideas, through: :like_ideas

  has_many :rating_ideas
  has_many :rated_ideas, through: :rating_ideas

  has_many :tags
  has_many :attached_tags, through: :tags

  validates :provider, presence: true
  validates :uid, presence: true, uniqueness: { scope: :provider }
  validates :name, presence: true
  validates :image_url, presence: true

  def self.find_or_create_from_auth_hash(auth_hash)
    provider = auth_hash[:provider]
    uid = auth_hash[:uid]

    case provider
    when 'google'
      name = auth_hash[:info][:name]
      image_url = auth_hash[:info][:image]
    when 'github'
      name = auth_hash[:info][:nickname]
      image_url = auth_hash[:info][:image]
    when 'twitter'
      name = auth_hash[:info][:nickname]
      image_url = auth_hash[:info][:image]
    end

    User.find_or_create_by(provider: provider, uid: uid) do |user|
      user.name = name
      user.image_url = image_url
    end
  end

  def like!(idea)
    like_ideas.create!(idea_id: idea.id)
  end

  def unlike!(idea)
    like_ideas.find_by(idea_id: idea.id).destroy
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  private

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

  def signed_in?
    !!session[:user_id]
  end

  def authenticate
    return if signed_in?
    redirect_to root_path, alert: 'Please sign in'
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def about
  end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  before_action :authenticate, except: [:index, :show]
  before_action :set_type

  def index
    @ideas = type_class.order('created_at DESC, id DESC').page(params[:page])
  end

  def new
    @idea = current_user.submitted_ideas.build
  end

  def create
    @idea = current_user.submitted_ideas.build(idea_params)
    if @idea.save
      @idea.rate!(current_user, :impact, params[:idea][:impact])
      @idea.rate!(current_user, :frequency, params[:idea][:frequency])

      redirect_to @idea, notice: 'Submitted'
    else
      render :new
    end
  end

  def show
    @idea = Idea.find(params[:id])

    if signed_in?
      @rating = @idea.rating_ideas.find_by(user_id: current_user.id)
    end
  end

  def edit
    @idea = current_user.submitted_ideas.find(params[:id])
    @rating = @idea.rating_ideas.find_by(user_id: current_user.id)
  end

  def update
    @idea = current_user.submitted_ideas.find(params[:id])
    if @idea.update(idea_params)
      @idea.rate!(current_user, :impact, params[:idea][:impact])
      @idea.rate!(current_user, :frequency, params[:idea][:frequency])

      redirect_to @idea, notice: 'Updated'
    else
      render :edit
    end
  end

  def destroy
    @idea = current_user.submitted_ideas.find(params[:id])
    @idea.destroy!
    redirect_to root_path, notice: 'Deleted'
  end

  def sort
    idea = Idea.find(params[:idea_id])
    idea.update(idea_params)
    render nothing: true
  end

  def unlike
    idea = Idea.find(params[:idea_id])
    current_user.unlike!(idea)
    render nothing: true
  end

  private

  def idea_params
    params.require(:idea).permit(
      :title, :description, :attached_tags, :file, :file_cache, :remove_file, :row_order_position
    )
  end

  def set_type
     @type = type
  end

  def type
    Idea.types.include?(params[:type]) ? params[:type] : "Idea"
  end

  def type_class
    type.constantize
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_or_create_from_auth_hash(request.env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_path, flash: {success: 'Signed in'}
  end

  def destroy
    reset_session
    redirect_to root_path, flash: {success: 'Signed out'}
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
    render 'index', formats: :json, handlers: :jbuilder
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @ideas = @user.ideas.rank(:row_order)
  end

end

app/helpers/application_helper.rb
require 'uri'

module ApplicationHelper

  def timeago(time, options = {})
    options[:class] ||= "timeago"
    content_tag(:abbr, time.to_s, options.merge(:title => time.getutc.iso8601)) if time
  end

  def bootstrap_class_for(level)
    case level
      when "success" then "alert-success"
      when "notice"  then "alert-info"
      when "alert"   then "alert-warning"
      when "error"   then "alert-danger"
    end
  end

  def filename(file)
    URI.decode(File::basename(file.to_s))
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_info.html.slim
.panel.panel-info
  .panel-heading
    h4 Most viewed problems
  .panel-body
    | ...

.panel.panel-info
  .panel-heading
    h4 Recently updated problems
  .panel-body
    | ...

app/views/home/about.html.slim
.page-header
  h2 About probless

br

p There are three reasons that this web service is being developed.

.explanation
  ol
    li Create ideas from problems, not from solutions
    p We as techies sometimes or often create new ideas which are based on technologies. However, such ideas from technologies as seeds do not always solve big and/or ciritcal problems from other people's needs, because the ideas are created just for utilizing the technologies first, not for solving problems. This might be one of root causes that nobody want such ideas.
    p So, we need to start creating ideas from problems which someone really want to solve. This probless helps to collect problems from anyone, and let other ones know that there are same problems which you also have. probless also shows how many people agree with the problems that explain which problems need to be solved with priority.
    p Our life is not so long. We have to focus on highly prioritized problems rather than low ones.
    li Ideas meet other ideas
    p TBD
    li Find collaborators who want to solve problems together
    p This probless also show solutions for problems, and help to find other people who really want to solve problems together. Or, anyone can propose better solution than other ones.
    p Such collaborations and/or productive discussions are expected in this probless to make people, both who had problems and who solved problems, happy

app/views/home/index.html.slim
- if signed_in?

  = render "info"

- else

  .jumbotron
    .container
      h1 Let's minimize problems as less as possible!
      p This web service is designed to seek big problems, think great solutions and solve problems with collaborators.
      p
        = link_to "Learn more »", about_path, class: "btn btn-primary btn-lg"

  .container#about
    .row
      .col-md-4
        .row
          .col-md-1.col-md-offset-3
            i.fa.fa-search
        h3 Think from problems
        p In order to truely focus on what users really want to solve, let's think about ideas from problems first, not from solutions.
      .col-md-4
        .row
          .col-md-1.col-md-offset-3
            i.fa.fa-comments-o
        h3 Meet other ideas
        p This is an idea database that problems and solutions can be inspired by others, and that might be eventually innovation.
      .col-md-4
        .row
          .col-md-1.col-md-offset-3
            i.fa.fa-group
        h3 Solve problem together
        p This is also a community that you can find collaborators who want to solve problem together.

app/views/ideas/_form.html.slim
= form_for(idea, class: 'form-horizontal', role: 'form') do |f|
  - if idea.errors.any?
    .alert.alert-danger
      ul
        - idea.errors.full_messages.each do |msg|
          li #{msg}

  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'

  .form-group
    = f.label :description
    ul.nav.nav-tabs role="tablist"
      li.active
        a href="#write" role="tab" data-toggle="tab"
          | Write
      li
        a href="#preview" role="tab" data-toggle="tab"
          | Preview

    .tab-content
      .tab-pane.fade.in.active#write
        = f.text_area :description, class: 'form-control', rows: 10
      .tab-pane.fade#preview
        br
        #markdown

  .form-group
    = f.label "Attached file"
    - if idea.file?
      div
        = filename(idea.file)
        => f.check_box :remove_file
        | Remove this file
    = f.file_field :file
    = f.hidden_field :file_cache

  .form-group
    = f.label "Tags"
    .tags
    input(type="text" class="form-control autocomplete")
    = f.hidden_field :tags

  .form-group
    = f.label "Rating"
    br
    span.rating-label
      | Impact
    - for i in 1..5
      label.checkbox-inline
        - if rating && i == rating.impact
          input(type="radio" name="idea[impact]" value="#{i}" checked)  #{i}
        - else
          input(type="radio" name="idea[impact]" value="#{i}")          #{i}
    br
    span.rating-label
      | Frequency
    - for i in 1..5
      label.checkbox-inline
        - if rating && i == rating.frequency
          input(type="radio" name="idea[frequency]" value="#{i}" checked)  #{i}
        - else
          input(type="radio" name="idea[frequency]" value="#{i}")          #{i}

  => f.submit task, class: 'btn btn-primary', data: { disable_with: 'Processing...' }
  = link_to 'Cancel', idea, class: "btn btn-default"

app/views/ideas/_idea.html.slim
= link_to(idea, class: "list-group-item list-item", data: { model_name: idea.class.name.underscore, update_url: idea_sort_path(idea), delete_url: idea_unlike_path(idea) })
  h4.list-group-item-heading
    = idea.title

  .list-group-item-text.clearfix
    p.ellipsis
      - if idea.description?
        = Markdown.to_text(idea.description)

    .pull-right
      = timeago(idea.created_at)
      - if idea.owner
        => image_tag idea.owner_image_url, class: "gravatar"
        = idea.owner_name

    span.icon
      i.fa.fa-thumbs-up
      = idea.liked_users.count

    - if idea.file?
      span.icon
        i.fa.fa-file-text-o

app/views/ideas/_rating.html.slim
.rating
  table
    - for y in 1..5
      tr
        - for x in 1..5
          - if rating && rating.impact == (6 - y) && rating.frequency == x
            td: i.fa.fa-star
          - else
            td

app/views/ideas/_relating_idea.html.slim
br
br
hr
h3 Related ideas

.list-group
  - idea.relating_ideas.each do |relating_idea|
    = render "idea", idea: relating_idea

app/views/ideas/edit.html.slim
.page-header
  h2 Edit problem

= render 'form', idea: @idea, rating: @rating, task: 'Update'

app/views/ideas/index.html.slim
.page-header
  h2 Problems

= paginate @ideas

.list-group
  = render @ideas

= paginate @ideas

app/views/ideas/new.html.slim
.page-header
  h2 Submit problem

= render 'form', idea: @idea, rating: nil, task: 'Submit'

app/views/ideas/show.html.slim
.page-header
  h2 #{@idea.title}

.panel.panel-default
  .panel-heading
    | Submitter
  .panel-body
    - if @idea.owner
      => image_tag @idea.owner_image_url, class: "gravatar"
      = @idea.owner_name

.panel.panel-default
  .panel-heading
    | Description
  .panel-body
    - if @idea.description?
      = Markdown.to_html(@idea.description)

- if @idea.file?
  .panel.panel-default
    .panel-heading
      | Attached file
    .panel-body
      = link_to filename(@idea.file), @idea.file.url

.panel.panel-default
  .panel-heading
    | Rating
  .panel-body
    = render "rating", rating: @rating

.panel.panel-default
  .panel-heading
    | Like
  .panel-body
    - @idea.liked_users.each do |user|
      = link_to "#{user.name}", user_path(user)
      = user != @idea.liked_users.last ? ", " : ""

- if @idea.submitted_by?(current_user)
  => link_to 'Edit idea', edit_idea_path(@idea), class: 'btn btn-info'
  = link_to 'Delete idea', idea_path(@idea), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?'}

/ = render "relating_idea", idea: @idea

app/views/layouts/_footer.html.slim
footer
  .container
    br
    hr

    p &copy; 2014 Ikuo Terado

app/views/layouts/_header.html.slim
header.navbar.navbar-default role="navigation"
  .container
    .navbar-header
      button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to "probless", root_path, class: "navbar-brand", id: "logo"

    .collapse.navbar-collapse#bs-example-navbar-collapse-1

      ul.nav.navbar-nav
        li
          = link_to "About", about_path
        li
          = link_to "Problems", problems_path
        li
          = link_to "Solutions", problems_path

      ul.nav.navbar-nav.navbar-right
        li
          .dropdown
            button.btn.btn-default.dropdown-toggle#dropdownMenu0 type="button" data-toggle="dropdown"
              | Submit
              span.caret<
            ul.dropdown-menu role="menu" aria-labelledby="dropdownMenu0"
              li role="presentation"
                = link_to "Problem", new_problem_path

        - if signed_in?
          li
            .dropdown
              button.btn.btn-default.dropdown-toggle#dropdownMenu1 type="button" data-toggle="dropdown"
                = image_tag current_user.image_url, class: "gravatar"
                = current_user.name
                span.caret<
              ul.dropdown-menu role="menu" aria-labelledby="dropdownMenu1"
                li role="presentation"
                  = link_to "User info", user_path(current_user.id)
                li.divider role="presentation"
                li role="presentation"
                  = link_to "Sign out", logout_path
        - else
          li
            .dropdown
              button.btn.btn-success.dropdown-toggle#dropdownMenu2 type="button" data-toggle="dropdown"
                | Sign in
                span.caret<
              ul.dropdown-menu role="menu" aria-labelledby="dropdownMenu2"
                li role="presentation"
                  = link_to("/auth/google") do
                    i.fa.fa-google-plus>
                    | Google
                li role="presentation"
                  = link_to("/auth/github") do
                    i.fa.fa-github>
                    | GitHub
                li role="presentation"
                  = link_to("/auth/twitter") do
                    i.fa.fa-twitter>
                    | Twitter

app/views/layouts/application.html.slim
doctype html
html
  head
    title probless
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    = render partial: 'layouts/header'

    .container
      - flash.each do |key, value|
        .alert.alert-dismissible class="#{bootstrap_class_for(key)}"
          button.close type="button" data-dismiss="alert"
            span aria-hidden="true"
              | &times;
            span.sr-only
              | Close
          = value

      = yield

    = render partial: 'layouts/footer'

app/views/problems/_form.html.slim
= form_for(problem, class: 'form-horizontal', role: 'form') do |f|
  - if problem.errors.any?
    .alert.alert-danger
      ul
        - problem.errors.full_messages.each do |msg|
          li #{msg}

  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'

  .form-group
    = f.label :description
    ul.nav.nav-tabs role="tablist"
      li.active
        a href="#write" role="tab" data-toggle="tab"
          | Write
      li
        a href="#preview" role="tab" data-toggle="tab"
          | Preview

    .tab-content
      .tab-pane.fade.in.active#write
        = f.text_area :description, class: 'form-control', rows: 10
      .tab-pane.fade#preview

  .form-group
    = f.label "Attached file"
    - if problem.file?
      div
        = filename(problem.file)
        => f.check_box :remove_file
        | Remove this file
    = f.file_field :file
    = f.hidden_field :file_cache

  .form-group
    = f.label "Rating"
    br
    span.rating-label
      | Impact
    - for i in 1..5
      label.checkbox-inline
        - if rating && i == rating.impact
          input(type="radio" name="problem[impact]" value="#{i}" checked)  #{i}
        - else
          input(type="radio" name="problem[impact]" value="#{i}")          #{i}
    br
    span.rating-label
      | Frequency
    - for i in 1..5
      label.checkbox-inline
        - if rating && i == rating.frequency
          input(type="radio" name="problem[frequency]" value="#{i}" checked)  #{i}
        - else
          input(type="radio" name="problem[frequency]" value="#{i}")          #{i}

  => f.submit task, class: 'btn btn-primary', data: { disable_with: 'Processing...' }
  = link_to 'Cancel', problem, class: "btn btn-default"

app/views/problems/_item.html.erb
<%= link_to(problem, class: 'list-group-item') do %>
  <h4 class="list-group-item-heading">
    <%= problem.title %>
  </h4>

  <div class="list-group-item-text clearfix">
    <%= Markdown.to_text(problem.description) %>

    <div class="pull-right">
      <%= problem.created_at %>
      <%= image_tag problem.owner.image_url %>
      <%= problem.owner.name %>
    </div>
  </div>
<% end %>

app/views/users/_ideas.html.slim
.panel.panel-info
  .panel-heading
    - if sortable
      .trash.connectedSortable.pull-right
        h4: i.fa.fa-trash-o
    h4 Interesting problems

  .list-group class=(sortable ? 'list-sortable connectedSortable' : '')
    = render ideas

app/views/users/_problems.html.slim
.panel.panel-info
  .panel-heading
    - if sortable
      .trash.connectedSortable.pull-right
        h4: i.fa.fa-trash-o
    h4 Interesting problems

  .list-group class=(sortable ? 'list-sortable connectedSortable' : '')
    = render problems

app/views/users/_user.html.slim
= render "users/ideas", sortable: false

app/views/users/show.html.slim
.page-header
  h2
    => image_tag @user.image_url, class: "gravatar"
    = @user.name

br

= render "users/ideas", ideas: @ideas, sortable: true